In [1]:
from math import *
import numpy as np

zenith = radians(25)
azimuth = radians(30)

paleoazimuth = radians(50)

THETA = radians(50)


In [22]:
def constrain(sl_pt, az_pt, az_line):
    x = tan(sl_pt) * (cos(az_pt) + tan(az_line) * sin(az_pt)) * sin(2 * az_line) / 2
    y = x / tan(az_line)
    return atan(sqrt(x**2 + y**2))

def great_circle_distance(sl1, az1, sl2, az2):
    return acos(cos(sl1)*cos(sl2) + sin(sl1)*sin(sl2)*cos(az1-az2))

def spherical_to_cartesian(sl, az):
    return np.array([sin(sl)*cos(az),sin(sl)*sin(az),cos(sl)])

def cartesian_to_spherical(vector):
    rho = sqrt(np.sum(vector**2))
    az = atan2(vector[1],vector[0])
    sl = acos(vector[2] / rho)
    return np.array([sl, az])

def z_rotation_3d(theta):
    return np.array([[cos(theta),-sin(theta), 0],
                     [sin(theta), cos(theta), 0],
                     [0,          0,          1]])

print(z_rotation_3d(4*pi/3) @ np.array([1,0,2]))

def project_radial(vector,projection_plane_angle):
    rotated_vector = z_rotation_3d(projection_plane_angle)
    projection = 1



[-0.5       -0.8660254  2.       ]


In [3]:
paleozenith = constrain(zenith, azimuth, paleoazimuth)
degrees(paleozenith)

(great_circle_distance(zenith, azimuth, paleozenith, paleoazimuth))

0.14505207542240153

In [4]:
THETA = 50

pt2 = spherical_to_cartesian(zenith, azimuth)
pt1 = spherical_to_cartesian(paleozenith,paleoazimuth)
axis = np.cross(pt1,pt2)
axis

array([ 0.08509971,  0.10141788, -0.05801215])

In [5]:
cartesian_to_spherical(axis)*180/pi

array([113.66235329,  50.        ])

In [6]:
angle = asin(sqrt(np.sum(axis**2)))
unit_axis = axis / sqrt(np.sum(axis**2))

angle

0.14505207542240117

In [7]:
np.outer(unit_axis, unit_axis)

array([[ 0.34662209,  0.41308813, -0.23629096],
       [ 0.41308813,  0.49229926, -0.2816006 ],
       [-0.23629096, -0.2816006 ,  0.16107865]])

In [8]:
def rotation(axis):
    '''Minimum rotation p' -> p: z-hat -> ?'''
    u = axis / sqrt(np.sum(axis**2))
    ang = asin(sqrt(np.sum(axis**2)))
    z = np.array([0,0,1])
    cross = np.cross(z,u)
    return u*np.dot(u,z)+cos(ang)*np.cross(cross,u)+sin(ang)*cross

In [9]:
print(rotation(axis))

[-0.57151837 -0.47514423 -0.66903267]


In [10]:
cartesian_to_spherical(rotation(axis))

array([ 2.30370283, -2.44801314])